CREATE DATABASE mozflyg;
USE mozflyg;

CREATE TABLE airport (
id SMALLINT(5) AUTO_INCREMENT NOT NULL,
name CHAR(128) DEFAULT NULL,
city CHAR(128) DEFAULT NULL,
PRIMARY KEY (id)
);

CREATE TABLE account (
id SMALLINT(5) AUTO_INCREMENT NOT NULL,
username CHAR(128) NOT NULL,
password CHAR(128) NOT NULL,
isAdmin BOOLEAN DEFAULT 0,
PRIMARY KEY (id)
);